import { IOption } from '../../components/lib/Dropdown/Dropdown';

export const occupationList: Array<IOption> = [
	{text: 'Select', value: 'Select'},
	{text: "Academic librarian", value: "Academic librarian"},
	{text: "Accountant", value: "Accountant"},
	{text: "Accounting technician", value: "Accounting technician"},
	{text: "Actuary", value: "Actuary"},
	{text: "Adult nurse", value: "Adult nurse"},
	{text: "Advertising account executive", value: "Advertising account executive"},
	{text: "Advertising account planner", value: "Advertising account planner"},
	{text: "Advertising copywriter", value: "Advertising copywriter"},
	{text: "Advice worker", value: "Advice worker"},
	{text: "Advocate (Scotland)", value: "Advocate (Scotland)"},
	{text: "Aeronautical engineer", value: "Aeronautical engineer"},
	{text: "Agricultural consultant", value: "Agricultural consultant"},
	{text: "Agricultural manager", value: "Agricultural manager"},
	{text: "Aid worker/humanitarian worker", value: "Aid worker/humanitarian worker"},
	{text: "Air traffic controller", value: "Air traffic controller"},
	{text: "Airline cabin crew", value: "Airline cabin crew"},
	{text: "Amenity horticulturist", value: "Amenity horticulturist"},
	{text: "Analytical chemist", value: "Analytical chemist"},
	{text: "Animal nutritionist", value: "Animal nutritionist"},
	{text: "Animator", value: "Animator"},
	{text: "Archaeologist", value: "Archaeologist"},
	{text: "Architect", value: "Architect"},
	{text: "Architectural technologist", value: "Architectural technologist"},
	{text: "Archivist", value: "Archivist"},
	{text: "Armed forces officer", value: "Armed forces officer"},
	{text: "Aromatherapist", value: "Aromatherapist"},
	{text: "Art therapist", value: "Art therapist"},
	{text: "Arts administrator", value: "Arts administrator"},
	{text: "Auditor", value: "Auditor"},
	{text: "Automotive engineer", value: "Automotive engineer"},
	{text: "Barrister", value: "Barrister"},
	{text: "Barrister’s clerk", value: "Barrister’s clerk"},
	{text: "Bilingual secretary", value: "Bilingual secretary"},
	{text: "Biomedical engineer", value: "Biomedical engineer"},
	{text: "Biomedical scientist", value: "Biomedical scientist"},
	{text: "Biotechnologist", value: "Biotechnologist"},
	{text: "Brand manager", value: "Brand manager"},
	{text: "Broadcasting presenter", value: "Broadcasting presenter"},
	{text: "Building control officer/surveyor", value: "Building control officer/surveyor"},
	{text: "Building services engineer", value: "Building services engineer"},
	{text: "Building surveyor", value: "Building surveyor"},
	{text: "Camera operator", value: "Camera operator"},
	{text: "Careers adviser (higher education)", value: "Careers adviser (higher education)"},
	{text: "Careers adviser", value: "Careers adviser"},
	{text: "Careers consultant", value: "Careers consultant"},
	{text: "Cartographer", value: "Cartographer"},
	{text: "Catering manager", value: "Catering manager"},
	{text: "Charities administrator", value: "Charities administrator"},
	{text: "Charities fundraiser", value: "Charities fundraiser"},
	{text: "Chemical (process) engineer", value: "Chemical (process) engineer"},
	{text: "Child psychotherapist", value: "Child psychotherapist"},
	{text: "Children's nurse", value: "Children's nurse"},
	{text: "Chiropractor", value: "Chiropractor"},
	{text: "Civil engineer", value: "Civil engineer"},
	{text: "Civil Service administrator", value: "Civil Service administrator"},
	{text: "Clinical biochemist", value: "Clinical biochemist"},
	{text: "Clinical cytogeneticist", value: "Clinical cytogeneticist"},
	{text: "Clinical microbiologist", value: "Clinical microbiologist"},
	{text: "Clinical molecular geneticist", value: "Clinical molecular geneticist"},
	{text: "Clinical research associate", value: "Clinical research associate"},
	{text: "Clinical scientist - tissue typing", value: "Clinical scientist - tissue typing"},
	{text: "Clothing and textile technologist", value: "Clothing and textile technologist"},
	{text: "Colour technologist", value: "Colour technologist"},
	{text: "Commercial horticulturist", value: "Commercial horticulturist"},
	{text: "Commercial/residential/rural surveyor", value: "Commercial/residential/rural surveyor"},
	{text: "Commissioning editor", value: "Commissioning editor"},
	{text: "Commissioning engineer", value: "Commissioning engineer"},
	{text: "Commodity broker", value: "Commodity broker"},
	{text: "Communications engineer", value: "Communications engineer"},
	{text: "Community arts worker", value: "Community arts worker"},
	{text: "Community education officer", value: "Community education officer"},
	{text: "Community worker", value: "Community worker"},
	{text: "Company secretary", value: "Company secretary"},
	{text: "Computer sales support", value: "Computer sales support"},
	{text: "Computer scientist", value: "Computer scientist"},
	{text: "Conference organiser", value: "Conference organiser"},
	{text: "Consultant", value: "Consultant"},
	{text: "Consumer rights adviser", value: "Consumer rights adviser"},
	{text: "Control and instrumentation engineer", value: "Control and instrumentation engineer"},
	{text: "Corporate banker", value: "Corporate banker"},
	{text: "Corporate treasurer", value: "Corporate treasurer"},
	{text: "Counsellor", value: "Counsellor"},
	{text: "Courier/tour guide", value: "Courier/tour guide"},
	{text: "Court reporter/verbatim reporter", value: "Court reporter/verbatim reporter"},
	{text: "Credit analyst", value: "Credit analyst"},
	{text: "Crown Prosecution Service lawyer", value: "Crown Prosecution Service lawyer"},
	{text: "Crystallographer", value: "Crystallographer"},
	{text: "Curator", value: "Curator"},
	{text: "Customs officer", value: "Customs officer"},
	{text: "Cyber security specialist", value: "Cyber security specialist"},
	{text: "Dance movement therapist", value: "Dance movement therapist"},
	{text: "Data analyst", value: "Data analyst"},
	{text: "Data scientist", value: "Data scientist"},
	{text: "Data visualisation analyst", value: "Data visualisation analyst"},
	{text: "Database administrator", value: "Database administrator"},
	{text: "Debt/finance adviser", value: "Debt/finance adviser"},
	{text: "Dental hygienist", value: "Dental hygienist"},
	{text: "Dentist", value: "Dentist"},
	{text: "Design engineer", value: "Design engineer"},
	{text: "Dietitian", value: "Dietitian"},
	{text: "Diplomatic service", value: "Diplomatic service"},
	{text: "Doctor (general practitioner, GP)", value: "Doctor (general practitioner, GP)"},
	{text: "Doctor (hospital)", value: "Doctor (hospital)"},
	{text: "Dramatherapist", value: "Dramatherapist"},
	{text: "Economist", value: "Economist"},
	{text: "Editorial assistant", value: "Editorial assistant"},
	{text: "Education administrator", value: "Education administrator"},
	{text: "Electrical engineer", value: "Electrical engineer"},
	{text: "Electronics engineer", value: "Electronics engineer"},
	{text: "Employment advice worker", value: "Employment advice worker"},
	{text: "Energy conservation officer", value: "Energy conservation officer"},
	{text: "Engineering geologist", value: "Engineering geologist"},
	{text: "Environmental education officer", value: "Environmental education officer"},
	{text: "Environmental health officer", value: "Environmental health officer"},
	{text: "Environmental manager", value: "Environmental manager"},
	{text: "Environmental scientist", value: "Environmental scientist"},
	{text: "Equal opportunities officer", value: "Equal opportunities officer"},
	{text: "Equality and diversity officer", value: "Equality and diversity officer"},
	{text: "Ergonomist", value: "Ergonomist"},
	{text: "Estate agent", value: "Estate agent"},
	{text: "European Commission administrators", value: "European Commission administrators"},
	{text: "Exhibition display designer", value: "Exhibition display designer"},
	{text: "Exhibition organiser", value: "Exhibition organiser"},
	{text: "Exploration geologist", value: "Exploration geologist"},
	{text: "Facilities manager", value: "Facilities manager"},
	{text: "Field trials officer", value: "Field trials officer"},
	{text: "Financial manager", value: "Financial manager"},
	{text: "Firefighter", value: "Firefighter"},
	{text: "Fisheries officer", value: "Fisheries officer"},
	{text: "Fitness centre manager", value: "Fitness centre manager"},
	{text: "Food scientist", value: "Food scientist"},
	{text: "Food technologist", value: "Food technologist"},
	{text: "Forensic scientist", value: "Forensic scientist"},
	{text: "Geneticist", value: "Geneticist"},
	{text: "Geographical information systems manager", value: "Geographical information systems manager"},
	{text: "Geomatics/land surveyor", value: "Geomatics/land surveyor"},
	{text: "Government lawyer", value: "Government lawyer"},
	{text: "Government research officer", value: "Government research officer"},
	{text: "Graphic designer", value: "Graphic designer"},
	{text: "Health and safety adviser", value: "Health and safety adviser"},
	{text: "Health and safety inspector", value: "Health and safety inspector"},
	{text: "Health promotion specialist", value: "Health promotion specialist"},
	{text: "Health service manager", value: "Health service manager"},
	{text: "Health visitor", value: "Health visitor"},
	{text: "Herbalist", value: "Herbalist"},
	{text: "Heritage manager", value: "Heritage manager"},
	{text: "Higher education administrator", value: "Higher education administrator"},
	{text: "Higher education advice worker", value: "Higher education advice worker"},
	{text: "Homeless worker", value: "Homeless worker"},
	{text: "Horticultural consultant", value: "Horticultural consultant"},
	{text: "Hotel manager", value: "Hotel manager"},
	{text: "Housing adviser", value: "Housing adviser"},
	{text: "Human resources officer", value: "Human resources officer"},
	{text: "Hydrologist", value: "Hydrologist"},
	{text: "Illustrator", value: "Illustrator"},
	{text: "Immigration officer", value: "Immigration officer"},
	{text: "Immunologist", value: "Immunologist"},
	{text: "Industrial/product designer", value: "Industrial/product designer"},
	{text: "Information scientist", value: "Information scientist"},
	{text: "Information systems manager", value: "Information systems manager"},
	{text: "Information technology/software trainers", value: "Information technology/software trainers"},
	{text: "Insurance broker", value: "Insurance broker"},
	{text: "Insurance claims inspector", value: "Insurance claims inspector"},
	{text: "Insurance risk surveyor", value: "Insurance risk surveyor"},
	{text: "Insurance underwriter", value: "Insurance underwriter"},
	{text: "Interpreter", value: "Interpreter"},
	{text: "Investment analyst", value: "Investment analyst"},
	{text: "Investment banker - corporate finance", value: "Investment banker - corporate finance"},
	{text: "Investment banker – operations", value: "Investment banker – operations"},
	{text: "Investment fund manager", value: "Investment fund manager"},
	{text: "IT consultant", value: "IT consultant"},
	{text: "IT support analyst", value: "IT support analyst"},
	{text: "Journalist", value: "Journalist"},
	{text: "Laboratory technician", value: "Laboratory technician"},
	{text: "Land-based engineer", value: "Land-based engineer"},
	{text: "Landscape architect", value: "Landscape architect"},
	{text: "Learning disability nurse", value: "Learning disability nurse"},
	{text: "Learning mentor", value: "Learning mentor"},
	{text: "Lecturer (adult education)", value: "Lecturer (adult education)"},
	{text: "Lecturer (further education)", value: "Lecturer (further education)"},
	{text: "Lecturer (higher education)", value: "Lecturer (higher education)"},
	{text: "Legal executive", value: "Legal executive"},
	{text: "Leisure centre manager", value: "Leisure centre manager"},
	{text: "Licensed conveyancer", value: "Licensed conveyancer"},
	{text: "Local government administrator", value: "Local government administrator"},
	{text: "Local government lawyer", value: "Local government lawyer"},
	{text: "Logistics/distribution manager", value: "Logistics/distribution manager"},
	{text: "Magazine features editor", value: "Magazine features editor"},
	{text: "Magazine journalist", value: "Magazine journalist"},
	{text: "Maintenance engineer", value: "Maintenance engineer"},
	{text: "Management accountant", value: "Management accountant"},
	{text: "Manufacturing engineer", value: "Manufacturing engineer"},
	{text: "Manufacturing machine operator", value: "Manufacturing machine operator"},
	{text: "Manufacturing toolmaker", value: "Manufacturing toolmaker"},
	{text: "Marine scientist", value: "Marine scientist"},
	{text: "Market research analyst", value: "Market research analyst"},
	{text: "Market research executive", value: "Market research executive"},
	{text: "Marketing account manager", value: "Marketing account manager"},
	{text: "Marketing assistant", value: "Marketing assistant"},
	{text: "Marketing executive", value: "Marketing executive"},
	{text: "Marketing manager (social media)", value: "Marketing manager (social media)"},
	{text: "Materials engineer", value: "Materials engineer"},
	{text: "Materials specialist", value: "Materials specialist"},
	{text: "Mechanical engineer", value: "Mechanical engineer"},
	{text: "Media analyst", value: "Media analyst"},
	{text: "Media buyer", value: "Media buyer"},
	{text: "Media planner", value: "Media planner"},
	{text: "Medical physicist", value: "Medical physicist"},
	{text: "Medical representative", value: "Medical representative"},
	{text: "Mental health nurse", value: "Mental health nurse"},
	{text: "Metallurgist", value: "Metallurgist"},
	{text: "Meteorologist", value: "Meteorologist"},
	{text: "Microbiologist", value: "Microbiologist"},
	{text: "Midwife", value: "Midwife"},
	{text: "Mining engineer", value: "Mining engineer"},
	{text: "Mobile developer", value: "Mobile developer"},
	{text: "Multimedia programmer", value: "Multimedia programmer"},
	{text: "Multimedia specialists", value: "Multimedia specialists"},
	{text: "Museum education officer", value: "Museum education officer"},
	{text: "Museum/gallery exhibition officer", value: "Museum/gallery exhibition officer"},
	{text: "Music therapist", value: "Music therapist"},
	{text: "Nanoscientist", value: "Nanoscientist"},
	{text: "Nature conservation officer", value: "Nature conservation officer"},
	{text: "Naval architect", value: "Naval architect"},
	{text: "Network administrator", value: "Network administrator"},
	{text: "Nurse", value: "Nurse"},
	{text: "Nutritional therapist", value: "Nutritional therapist"},
	{text: "Nutritionist", value: "Nutritionist"},
	{text: "Occupational therapist", value: "Occupational therapist"},
	{text: "Oceanographer", value: "Oceanographer"},
	{text: "Office manager", value: "Office manager"},
	{text: "Operational researcher", value: "Operational researcher"},
	{text: "Orthoptist", value: "Orthoptist"},
	{text: "Outdoor pursuits manager", value: "Outdoor pursuits manager"},
	{text: "Packaging technologist", value: "Packaging technologist"},
	{text: "Paediatric nurse", value: "Paediatric nurse"},
	{text: "Paramedic", value: "Paramedic"},
	{text: "Patent attorney", value: "Patent attorney"},
	{text: "Patent examiner", value: "Patent examiner"},
	{text: "Pension scheme manager", value: "Pension scheme manager"},
	{text: "Personal assistant", value: "Personal assistant"},
	{text: "Petroleum engineer", value: "Petroleum engineer"},
	{text: "Pharmacist", value: "Pharmacist"},
	{text: "Pharmacologist", value: "Pharmacologist"},
	{text: "Pharmacovigilance officer", value: "Pharmacovigilance officer"},
	{text: "Photographer", value: "Photographer"},
	{text: "Physiotherapist", value: "Physiotherapist"},
	{text: "Picture researcher", value: "Picture researcher"},
	{text: "Planning and development surveyor", value: "Planning and development surveyor"},
	{text: "Planning technician", value: "Planning technician"},
	{text: "Plant breeder", value: "Plant breeder"},
	{text: "Police officer", value: "Police officer"},
	{text: "Political party agent", value: "Political party agent"},
	{text: "Political party research officer", value: "Political party research officer"},
	{text: "Practice nurse", value: "Practice nurse"},
	{text: "Press photographer", value: "Press photographer"},
	{text: "Press sub-editor", value: "Press sub-editor"},
	{text: "Prison officer", value: "Prison officer"},
	{text: "Private music teacher", value: "Private music teacher"},
	{text: "Probation officer", value: "Probation officer"},
	{text: "Product development scientist", value: "Product development scientist"},
	{text: "Production manager", value: "Production manager"},
	{text: "Programme researcher", value: "Programme researcher"},
	{text: "Project manager", value: "Project manager"},
	{text: "Psychologist (clinical)", value: "Psychologist (clinical)"},
	{text: "Psychologist (educational)", value: "Psychologist (educational)"},
	{text: "Psychotherapist", value: "Psychotherapist"},
	{text: "Public affairs consultant (lobbyist)", value: "Public affairs consultant (lobbyist)"},
	{text: "Public affairs consultant (research)", value: "Public affairs consultant (research)"},
	{text: "Public house manager", value: "Public house manager"},
	{text: "Public librarian", value: "Public librarian"},
	{text: "Public relations (PR) officer", value: "Public relations (PR) officer"},
	{text: "QA analyst", value: "QA analyst"},
	{text: "Quality assurance manager", value: "Quality assurance manager"},
	{text: "Quantity surveyor", value: "Quantity surveyor"},
	{text: "Records manager", value: "Records manager"},
	{text: "Recruitment consultant", value: "Recruitment consultant"},
	{text: "Recycling officer", value: "Recycling officer"},
	{text: "Regulatory affairs officer", value: "Regulatory affairs officer"},
	{text: "Research chemist", value: "Research chemist"},
	{text: "Research scientist", value: "Research scientist"},
	{text: "Restaurant manager", value: "Restaurant manager"},
	{text: "Retail banker", value: "Retail banker"},
	{text: "Retail buyer", value: "Retail buyer"},
	{text: "Retail manager", value: "Retail manager"},
	{text: "Retail merchandiser", value: "Retail merchandiser"},
	{text: "Retail pharmacist", value: "Retail pharmacist"},
	{text: "Sales executive", value: "Sales executive"},
	{text: "Sales manager", value: "Sales manager"},
	{text: "Scene of crime officer", value: "Scene of crime officer"},
	{text: "Secretary", value: "Secretary"},
	{text: "Seismic interpreter", value: "Seismic interpreter"},
	{text: "Site engineer", value: "Site engineer"},
	{text: "Site manager", value: "Site manager"},
	{text: "Social researcher", value: "Social researcher"},
	{text: "Social worker", value: "Social worker"},
	{text: "Software developer", value: "Software developer"},
	{text: "Soil scientist", value: "Soil scientist"},
	{text: "Solicitor", value: "Solicitor"},
	{text: "Speech and language therapist", value: "Speech and language therapist"},
	{text: "Sports coach", value: "Sports coach"},
	{text: "Sports development officer", value: "Sports development officer"},
	{text: "Sports therapist", value: "Sports therapist"},
	{text: "Statistician", value: "Statistician"},
	{text: "Stockbroker", value: "Stockbroker"},
	{text: "Structural engineer", value: "Structural engineer"},
	{text: "Systems analyst", value: "Systems analyst"},
	{text: "Systems developer", value: "Systems developer"},
	{text: "Tax inspector", value: "Tax inspector"},
	{text: "Teacher (nursery/early years)", value: "Teacher (nursery/early years)"},
	{text: "Teacher (primary)", value: "Teacher (primary)"},
	{text: "Teacher (secondary)", value: "Teacher (secondary)"},
	{text: "Teacher (special educational needs)", value: "Teacher (special educational needs)"},
	{text: "Teaching/classroom assistant", value: "Teaching/classroom assistant"},
	{text: "Technical author", value: "Technical author"},
	{text: "Technical sales engineer", value: "Technical sales engineer"},
	{text: "TEFL/TESL teacher", value: "TEFL/TESL teacher"},
	{text: "Television production assistant", value: "Television production assistant"},
	{text: "Test automation developer", value: "Test automation developer"},
	{text: "Tour operator", value: "Tour operator"},
	{text: "Tourism officer", value: "Tourism officer"},
	{text: "Tourist information manager", value: "Tourist information manager"},
	{text: "Town and country planner", value: "Town and country planner"},
	{text: "Toxicologist", value: "Toxicologist"},
	{text: "Trade union research officer", value: "Trade union research officer"},
	{text: "Trader", value: "Trader"},
	{text: "Trading standards officer", value: "Trading standards officer"},
	{text: "Training and development officer", value: "Training and development officer"},
	{text: "Translator", value: "Translator"},
	{text: "Transportation planner", value: "Transportation planner"},
	{text: "Travel agent", value: "Travel agent"},
	{text: "TV/film/theatre set designer", value: "TV/film/theatre set designer"},
	{text: "UX designer", value: "UX designer"},
	{text: "Validation engineer", value: "Validation engineer"},
	{text: "Veterinary nurse", value: "Veterinary nurse"},
	{text: "Veterinary surgeon", value: "Veterinary surgeon"},
	{text: "Video game designer", value: "Video game designer"},
	{text: "Video game developer", value: "Video game developer"},
	{text: "Volunteer work organiser", value: "Volunteer work organiser"},
	{text: "Warehouse manager", value: "Warehouse manager"},
	{text: "Waste disposal officer", value: "Waste disposal officer"},
	{text: "Water conservation officer", value: "Water conservation officer"},
	{text: "Water engineer", value: "Water engineer"},
	{text: "Web designer", value: "Web designer"},
	{text: "Web developer", value: "Web developer"},
	{text: "Welfare rights adviser", value: "Welfare rights adviser"},
	{text: "Writer", value: "Writer"},
	{text: "Youth worker", value: "Youth worker"}
]
