import { IOption } from '../components/lib/Dropdown/Dropdown';

export const countryList: Array<IOption> = [
	{text: 'Afghanistan', value: 'Afghanistan'},
	{text: 'Albania', value: 'Albania'},
	{text: 'Algeria', value: 'Algeria'},
	{text: 'American Samoa', value: 'American Samoa'},
	{text: 'Andorra', value: 'Andorra'},
	{text: 'Angola', value: 'Angola'},
	{text: 'Anguilla', value: 'Anguilla'},
	{text: 'Antarctica', value: 'Antarctica'},
	{text: 'Antigua and Barbuda', value: 'Antigua and Barbuda'},
	{text: 'Argentina', value: 'Argentina'},
	{text: 'Armenia', value: 'Armenia'},
	{text: 'Aruba', value: 'Aruba'},
	{text: 'Australia', value: 'Australia'},
	{text: 'Austria', value: 'Austria'},
	{text: 'Azerbaijan', value: 'Azerbaijan'},
	{text: 'Bahamas (the)', value: 'Bahamas (the)'},
	{text: 'Bahrain', value: 'Bahrain'},
	{text: 'Bangladesh', value: 'Bangladesh'},
	{text: 'Barbados', value: 'Barbados'},
	{text: 'Belarus', value: 'Belarus'},
	{text: 'Belgium', value: 'Belgium'},
	{text: 'Belize', value: 'Belize'},
	{text: 'Benin', value: 'Benin'},
	{text: 'Bermuda', value: 'Bermuda'},
	{text: 'Bhutan', value: 'Bhutan'},
	{text: 'Bolivia (Plurinational State of)', value: 'Bolivia (Plurinational State of)'},
	{text: 'Bonaire, Sint Eustatius and Saba', value: 'Bonaire, Sint Eustatius and Saba'},
	{text: 'Bosnia and Herzegovina', value: 'Bosnia and Herzegovina'},
	{text: 'Botswana', value: 'Botswana'},
	{text: 'Bouvet Island', value: 'Bouvet Island'},
	{text: 'Brazil', value: 'Brazil'},
	{text: 'British Indian Ocean Territory (the)', value: 'British Indian Ocean Territory (the)'},
	{text: 'Brunei Darussalam', value: 'Brunei Darussalam'},
	{text: 'Bulgaria', value: 'Bulgaria'},
	{text: 'Burkina Faso', value: 'Burkina Faso'},
	{text: 'Burundi', value: 'Burundi'},
	{text: 'Cabo Verde', value: 'Cabo Verde'},
	{text: 'Cambodia', value: 'Cambodia'},
	{text: 'Cameroon', value: 'Cameroon'},
	{text: 'Canada', value: 'Canada'},
	{text: 'Cayman Islands (the)', value: 'Cayman Islands (the)'},
	{text: 'Central African Republic (the)', value: 'Central African Republic (the)'},
	{text: 'Chad', value: 'Chad'},
	{text: 'Chile', value: 'Chile'},
	{text: 'China', value: 'China'},
	{text: 'Christmas Island', value: 'Christmas Island'},
	{text: 'Cocos (Keeling) Islands (the)', value: 'Cocos (Keeling) Islands (the)'},
	{text: 'Colombia', value: 'Colombia'},
	{text: 'Comoros (the)', value: 'Comoros (the)'},
	{text: 'Congo (the Democratic Republic of the)', value: 'Congo (the Democratic Republic of the)'},
	{text: 'Congo (the)', value: 'Congo (the)'},
	{text: 'Cook Islands (the)', value: 'Cook Islands (the)'},
	{text: 'Costa Rica', value: 'Costa Rica'},
	{text: 'Croatia', value: 'Croatia'},
	{text: 'Cuba', value: 'Cuba'},
	{text: 'Curaçao', value: 'Curaçao'},
	{text: 'Cyprus', value: 'Cyprus'},
	{text: 'Czechia', value: 'Czechia'},
	{text: 'Côte dIvoire', value: 'Côte dIvoire'},
	{text: 'Denmark', value: 'Denmark'},
	{text: 'Djibouti', value: 'Djibouti'},
	{text: 'Dominica', value: 'Dominica'},
	{text: 'Dominican Republic (the)', value: 'Dominican Republic (the)'},
	{text: 'Ecuador', value: 'Ecuador'},
	{text: 'Egypt', value: 'Egypt'},
	{text: 'El Salvador', value: 'El Salvador'},
	{text: 'Equatorial Guinea', value: 'Equatorial Guinea'},
	{text: 'Eritrea', value: 'Eritrea'},
	{text: 'Estonia', value: 'Estonia'},
	{text: 'Eswatini', value: 'Eswatini'},
	{text: 'Ethiopia', value: 'Ethiopia'},
	{text: 'Falkland Islands (the) [Malvinas]', value: 'Falkland Islands (the) [Malvinas]'},
	{text: 'Faroe Islands (the)', value: 'Faroe Islands (the)'},
	{text: 'Fiji', value: 'Fiji'},
	{text: 'Finland', value: 'Finland'},
	{text: 'France', value: 'France'},
	{text: 'French Guiana', value: 'French Guiana'},
	{text: 'French Polynesia', value: 'French Polynesia'},
	{text: 'French Southern Territories (the)', value: 'French Southern Territories (the)'},
	{text: 'Gabon', value: 'Gabon'},
	{text: 'Gambia (the)', value: 'Gambia (the)'},
	{text: 'Georgia', value: 'Georgia'},
	{text: 'Germany', value: 'Germany'},
	{text: 'Ghana', value: 'Ghana'},
	{text: 'Gibraltar', value: 'Gibraltar'},
	{text: 'Greece', value: 'Greece'},
	{text: 'Greenland', value: 'Greenland'},
	{text: 'Grenada', value: 'Grenada'},
	{text: 'Guadeloupe', value: 'Guadeloupe'},
	{text: 'Guam', value: 'Guam'},
	{text: 'Guatemala', value: 'Guatemala'},
	{text: 'Guernsey', value: 'Guernsey'},
	{text: 'Guinea', value: 'Guinea'},
	{text: 'Guinea-Bissau', value: 'Guinea-Bissau'},
	{text: 'Guyana', value: 'Guyana'},
	{text: 'Haiti', value: 'Haiti'},
	{text: 'Heard Island and McDonald Islands', value: 'Heard Island and McDonald Islands'},
	{text: 'Holy See (the)', value: 'Holy See (the)'},
	{text: 'Honduras', value: 'Honduras'},
	{text: 'Hong Kong', value: 'Hong Kong'},
	{text: 'Hungary', value: 'Hungary'},
	{text: 'Iceland', value: 'Iceland'},
	{text: 'India', value: 'India'},
	{text: 'Indonesia', value: 'Indonesia'},
	{text: 'Iran (Islamic Republic of)', value: 'Iran (Islamic Republic of)'},
	{text: 'Iraq', value: 'Iraq'},
	{text: 'Ireland', value: 'Ireland'},
	{text: 'Isle of Man', value: 'Isle of Man'},
	{text: 'Israel', value: 'Israel'},
	{text: 'Italy', value: 'Italy'},
	{text: 'Jamaica', value: 'Jamaica'},
	{text: 'Japan', value: 'Japan'},
	{text: 'Jersey', value: 'Jersey'},
	{text: 'Jordan', value: 'Jordan'},
	{text: 'Kazakhstan', value: 'Kazakhstan'},
	{text: 'Kenya', value: 'Kenya'},
	{text: 'Kiribati', value: 'Kiribati'},
	{text: 'Korea (the Democratic People Republic of)', value: 'Korea (the Democratic People Republic of)'},
	{text: 'Korea (the Republic of)', value: 'Korea (the Republic of)'},
	{text: 'Kuwait', value: 'Kuwait'},
	{text: 'Kyrgyzstan', value: 'Kyrgyzstan'},
	{text: 'Lao People Democratic Republic (the)', value: 'Lao People Democratic Republic (the)'},
	{text: 'Latvia', value: 'Latvia'},
	{text: 'Lebanon', value: 'Lebanon'},
	{text: 'Lesotho', value: 'Lesotho'},
	{text: 'Liberia', value: 'Liberia'},
	{text: 'Libya', value: 'Libya'},
	{text: 'Liechtenstein', value: 'Liechtenstein'},
	{text: 'Lithuania', value: 'Lithuania'},
	{text: 'Luxembourg', value: 'Luxembourg'},
	{text: 'Macao', value: 'Macao'},
	{text: 'Madagascar', value: 'Madagascar'},
	{text: 'Malawi', value: 'Malawi'},
	{text: 'Malaysia', value: 'Malaysia'},
	{text: 'Maldives', value: 'Maldives'},
	{text: 'Mali', value: 'Mali'},
	{text: 'Malta', value: 'Malta'},
	{text: 'Marshall Islands (the)', value: 'Marshall Islands (the)'},
	{text: 'Martinique', value: 'Martinique'},
	{text: 'Mauritania', value: 'Mauritania'},
	{text: 'Mauritius', value: 'Mauritius'},
	{text: 'Mayotte', value: 'Mayotte'},
	{text: 'Mexico', value: 'Mexico'},
	{text: 'Micronesia (Federated States of)', value: 'Micronesia (Federated States of)'},
	{text: 'Moldova (the Republic of)', value: 'Moldova (the Republic of)'},
	{text: 'Monaco', value: 'Monaco'},
	{text: 'Mongolia', value: 'Mongolia'},
	{text: 'Montenegro', value: 'Montenegro'},
	{text: 'Montserrat', value: 'Montserrat'},
	{text: 'Morocco', value: 'Morocco'},
	{text: 'Mozambique', value: 'Mozambique'},
	{text: 'Myanmar', value: 'Myanmar'},
	{text: 'Namibia', value: 'Namibia'},
	{text: 'Nauru', value: 'Nauru'},
	{text: 'Nepal', value: 'Nepal'},
	{text: 'Netherlands (the)', value: 'Netherlands (the)'},
	{text: 'New Caledonia', value: 'New Caledonia'},
	{text: 'New Zealand', value: 'New Zealand'},
	{text: 'Nicaragua', value: 'Nicaragua'},
	{text: 'Niger (the)', value: 'Niger (the)'},
	{text: 'Nigeria', value: 'Nigeria'},
	{text: 'Niue', value: 'Niue'},
	{text: 'Norfolk Island', value: 'Norfolk Island'},
	{text: 'Northern Mariana Islands (the)', value: 'Northern Mariana Islands (the)'},
	{text: 'Norway', value: 'Norway'},
	{text: 'Oman', value: 'Oman'},
	{text: 'Pakistan', value: 'Pakistan'},
	{text: 'Palau', value: 'Palau'},
	{text: 'Palestine, State of', value: 'Palestine, State of'},
	{text: 'Panama', value: 'Panama'},
	{text: 'Papua New Guinea', value: 'Papua New Guinea'},
	{text: 'Paraguay', value: 'Paraguay'},
	{text: 'Peru', value: 'Peru'},
	{text: 'Philippines (the)', value: 'Philippines (the)'},
	{text: 'Pitcairn', value: 'Pitcairn'},
	{text: 'Poland', value: 'Poland'},
	{text: 'Portugal', value: 'Portugal'},
	{text: 'Puerto Rico', value: 'Puerto Rico'},
	{text: 'Qatar', value: 'Qatar'},
	{text: 'Republic of North Macedonia', value: 'Republic of North Macedonia'},
	{text: 'Romania', value: 'Romania'},
	{text: 'Russian Federation (the)', value: 'Russian Federation (the)'},
	{text: 'Rwanda', value: 'Rwanda'},
	{text: 'Réunion', value: 'Réunion'},
	{text: 'Saint Barthélemy', value: 'Saint Barthélemy'},
	{text: 'Saint Helena, Ascension and Tristan da Cunha', value: 'Saint Helena, Ascension and Tristan da Cunha'},
	{text: 'Saint Kitts and Nevis', value: 'Saint Kitts and Nevis'},
	{text: 'Saint Lucia', value: 'Saint Lucia'},
	{text: 'Saint Martin (French part)', value: 'Saint Martin (French part)'},
	{text: 'Saint Pierre and Miquelon', value: 'Saint Pierre and Miquelon'},
	{text: 'Saint Vincent and the Grenadines', value: 'Saint Vincent and the Grenadines'},
	{text: 'Samoa', value: 'Samoa'},
	{text: 'San Marino', value: 'San Marino'},
	{text: 'Sao Tome and Principe', value: 'Sao Tome and Principe'},
	{text: 'Saudi Arabia', value: 'Saudi Arabia'},
	{text: 'Senegal', value: 'Senegal'},
	{text: 'Serbia', value: 'Serbia'},
	{text: 'Seychelles', value: 'Seychelles'},
	{text: 'Sierra Leone', value: 'Sierra Leone'},
	{text: 'Singapore', value: 'Singapore'},
	{text: 'Sint Maarten (Dutch part)', value: 'Sint Maarten (Dutch part)'},
	{text: 'Slovakia', value: 'Slovakia'},
	{text: 'Slovenia', value: 'Slovenia'},
	{text: 'Solomon Islands', value: 'Solomon Islands'},
	{text: 'Somalia', value: 'Somalia'},
	{text: 'South Africa', value: 'South Africa'},
	{text: 'South Georgia and the South Sandwich Islands', value: 'South Georgia and the South Sandwich Islands'},
	{text: 'South Sudan', value: 'South Sudan'},
	{text: 'Spain', value: 'Spain'},
	{text: 'Sri Lanka', value: 'Sri Lanka'},
	{text: 'Sudan (the)', value: 'Sudan (the)'},
	{text: 'Suriname', value: 'Suriname'},
	{text: 'Svalbard and Jan Mayen', value: 'Svalbard and Jan Mayen'},
	{text: 'Sweden', value: 'Sweden'},
	{text: 'Switzerland', value: 'Switzerland'},
	{text: 'Syrian Arab Republic', value: 'Syrian Arab Republic'},
	{text: 'Taiwan', value: 'Taiwan'},
	{text: 'Tajikistan', value: 'Tajikistan'},
	{text: 'Tanzania, United Republic of', value: 'Tanzania, United Republic of'},
	{text: 'Thailand', value: 'Thailand'},
	{text: 'Timor-Leste', value: 'Timor-Leste'},
	{text: 'Togo', value: 'Togo'},
	{text: 'Tokelau', value: 'Tokelau'},
	{text: 'Tonga', value: 'Tonga'},
	{text: 'Trinidad and Tobago', value: 'Trinidad and Tobago'},
	{text: 'Tunisia', value: 'Tunisia'},
	{text: 'Turkey', value: 'Turkey'},
	{text: 'Turkmenistan', value: 'Turkmenistan'},
	{text: 'Turks and Caicos Islands (the)', value: 'Turks and Caicos Islands (the)'},
	{text: 'Tuvalu', value: 'Tuvalu'},
	{text: 'Uganda', value: 'Uganda'},
	{text: 'Ukraine', value: 'Ukraine'},
	{text: 'United Arab Emirates (the)', value: 'United Arab Emirates (the)'},
	{text: 'United Kingdom of Great Britain and Northern Ireland (the)', value: 'United Kingdom of Great Britain and Northern Ireland (the)'},
	{text: 'United States Minor Outlying Islands (the)', value: 'United States Minor Outlying Islands (the)'},
	{text: 'United States of America (the)', value: 'United States of America (the)'},
	{text: 'Uruguay', value: 'Uruguay'},
	{text: 'Uzbekistan', value: 'Uzbekistan'},
	{text: 'Vanuatu', value: 'Vanuatu'},
	{text: 'Venezuela (Bolivarian Republic of)', value: 'Venezuela (Bolivarian Republic of)'},
	{text: 'Viet Nam', value: 'Viet Nam'},
	{text: 'Virgin Islands (British)', value: 'Virgin Islands (British)'},
	{text: 'Virgin Islands (U.S.)', value: 'Virgin Islands (U.S.)'},
	{text: 'Wallis and Futuna', value: 'Wallis and Futuna'},
	{text: 'Western Sahara', value: 'Western Sahara'},
	{text: 'Yemen', value: 'Yemen'},
	{text: 'Zambia', value: 'Zambia'},
	{text: 'Zimbabwe', value: 'Zimbabwe'},
	{text: 'Åland Islands', value: 'Åland Islands'}
]
