export const FAQitems = [
  {title: "What hospitals and doctors can I use with Dsure?", description: "With our plans you are free to choose any hospital or doctor you want. We work with all hospitals, doctors, clinics, and laboratories as long as they are properly licensed and qualified to treat the condition. We treat all hospitals the same and work with all of them worldwide."},
  {title: "Do you have a network of medical facilities that work with Dsure?", description: "We provide our members a Direct Billing Network in a number of countries. Access is arranged via our third party administrators, Medical Administrators International, subject to prior approval and they will issue a Guarantee of Payment to the provider."},
  {title: "What happens if I get suddenly hospitalised and am saddled with a large hospital bill?", description: "We arrange direct settlement and guarantee of payments to nearly all hospitals in all corners of the globe. And that is our preferred method of handling any hospitalisation. Even if it takes someone personally delivering cash to a far flung hospital in the outback we can, in extreme circumstances, do that too."},
  {title: "After submitting a claim, how long does it take to get reimbursed?", description: "After submitting a claim, reimbursements can be expected within five to seven days through a bank transfer."},
  {title: "How do you treat pre-existing conditions?", description: "If you qualify for cover, pre-existing conditions are covered as any other medical condition. We do not exclude pre-existing conditions. However, if you are required to fill out an enrolment form as a pre-condition for cover, pre-existing conditions must be declared."},
  {title: "I am a digital nomad, why do you need my country of assignment for my International health insurance if I am moving countries regularly?", description: "We are only able to offer global medical insurance to people who spend the majority of their time outside of their home country. We therefore require you to provide your main country of assignment. If you are moving country regularly you can give us the country you are travelling to first or the country where you intend to stay the longest within your insured period. Your plan will cover you worldwide depending on the region you have chosen (including or excluding the USA and Canada). Please contact us if you need to change your cover region."},
  {title: "If I buy cover now will I be covered for Covid-19?", description: "Yes, we do not have any restrictions on pandemic diseases or outbreaks. You will be covered as a member with us from receipt of payment. We will provide benefits and coverage as per all the terms and conditions of the policy you have chosen."},
  {title: "Do you pay for a Covid vaccination?", description: "Yes, we cover for Covid vaccinations in countries where the state does not pick up the cost of the vaccination."},
];
